projects:
  chatterson:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: k7emoehdx5c3tg4vngs5gsijxy
      endpoints:
        prod: >-
          https://fat7zsq45bgs5cysqdn3e5cr3u.appsync-api.us-west-2.amazonaws.com/graphql
