projects:
  chatterson:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: tcbbweanufdiphxr6mgnggme4m
      endpoints:
        prod: >-
          https://hkyxdp3isjf67i2kky6rtfigb4.appsync-api.us-west-2.amazonaws.com/graphql
