projects:
  chatterson:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: 23sod57lwbanvjhuqxlisnalua
      endpoints:
        prod: >-
          https://jos4q2dzkzgbfgorglnivpuxtu.appsync-api.us-west-2.amazonaws.com/graphql
